
services:
  crawler:
    image: crawler:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - data:/app/data
      - data:/app/results

volumes:
  data:
